---
services:
  - docker

stages:
  - lint

jobs:
  include:
    - stage: lint
      script:
        # Lint the Dockerfile
        - docker run -it --rm -v "${PWD}/Dockerfile:/Dockerfile:ro" redcoolbeans/dockerlint
